# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insa_record', '0006_auto_20151001_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academic',
            old_name='graduated',
            new_name='academic_graduated',
        ),
        migrations.RenameField(
            model_name='academic',
            old_name='school_part',
            new_name='academic_school_part',
        ),
        migrations.RenameField(
            model_name='academic',
            old_name='school_title',
            new_name='academic_school_title',
        ),
        migrations.RenameField(
            model_name='academic',
            old_name='trial',
            new_name='academic_trial',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='apday',
            new_name='appoint_apday',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='part',
            new_name='appoint_part',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='position',
            new_name='appoint_position',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='type',
            new_name='appoint_type',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='work',
            new_name='appoint_work',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='job_position',
            new_name='career_job_position',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='job_type',
            new_name='career_job_type',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='oldjob',
            new_name='career_oldjob',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='retire_reason',
            new_name='career_retire_reason',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='trial',
            new_name='career_trial',
        ),
        migrations.RenameField(
            model_name='eduinfo',
            old_name='cost',
            new_name='edu_cost',
        ),
        migrations.RenameField(
            model_name='eduinfo',
            old_name='organization',
            new_name='edu_organization',
        ),
        migrations.RenameField(
            model_name='eduinfo',
            old_name='title',
            new_name='edu_title',
        ),
        migrations.RenameField(
            model_name='eduinfo',
            old_name='trial',
            new_name='edu_trial',
        ),
        migrations.RenameField(
            model_name='eduinfo',
            old_name='type',
            new_name='edu_type',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='academic',
            new_name='family_academic',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='birthday',
            new_name='family_birthday',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='job',
            new_name='family_job',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='myinfo',
            new_name='family_myinfo',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='name',
            new_name='family_name',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='relation',
            new_name='family_relation',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='together',
            new_name='family_together',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='getday',
            new_name='lang_getday',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='grade',
            new_name='lang_grade',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='lang_language',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='pubtest',
            new_name='lang_pubtest',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='score',
            new_name='lang_score',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='etc',
            new_name='license_etc',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='getday',
            new_name='license_getday',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='number',
            new_name='license_number',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='organization',
            new_name='license_organization',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='title',
            new_name='license_title',
        ),
        migrations.RenameField(
            model_name='rewardnpunish',
            old_name='punish_content',
            new_name='rnp_punish_content',
        ),
        migrations.RenameField(
            model_name='rewardnpunish',
            old_name='punish_date',
            new_name='rnp_punish_date',
        ),
        migrations.RenameField(
            model_name='rewardnpunish',
            old_name='punish_result',
            new_name='rnp_punish_result',
        ),
        migrations.RenameField(
            model_name='rewardnpunish',
            old_name='reward_content',
            new_name='rnp_reward_content',
        ),
        migrations.RenameField(
            model_name='rewardnpunish',
            old_name='reward_date',
            new_name='rnp_reward_date',
        ),
        migrations.RenameField(
            model_name='rewardnpunish',
            old_name='reward_result',
            new_name='rnp_reward_result',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='myinfo',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='myinfo',
        ),
        migrations.RemoveField(
            model_name='career',
            name='myinfo',
        ),
        migrations.RemoveField(
            model_name='eduinfo',
            name='myinfo',
        ),
        migrations.RemoveField(
            model_name='language',
            name='myinfo',
        ),
        migrations.RemoveField(
            model_name='license',
            name='myinfo',
        ),
        migrations.RemoveField(
            model_name='rewardnpunish',
            name='myinfo',
        ),
        migrations.AddField(
            model_name='academic',
            name='academic_myinfo',
            field=models.ForeignKey(to='insa_record.Myinfo', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appoint_myinfo',
            field=models.ForeignKey(to='insa_record.Myinfo', null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='career_myinfo',
            field=models.ForeignKey(to='insa_record.Myinfo', null=True),
        ),
        migrations.AddField(
            model_name='eduinfo',
            name='edu_myinfo',
            field=models.ForeignKey(to='insa_record.Myinfo', null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_myinfo',
            field=models.ForeignKey(to='insa_record.Myinfo', null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='license_myinfo',
            field=models.ForeignKey(to='insa_record.Myinfo', null=True),
        ),
        migrations.AddField(
            model_name='rewardnpunish',
            name='rnp_myinfo',
            field=models.ForeignKey(to='insa_record.Myinfo', null=True),
        ),
    ]
